file(GLOB_RECURSE SRC_FILES
    CONFIGURE_DEPENDS
    "${CMAKE_SOURCE_DIR}/src/*.cpp"
)

file(GLOB_RECURSE INCLUDE_FILES
    CONFIGURE_DEPENDS
    "${CMAKE_SOURCE_DIR}/include/*.hpp"
)

set(TEST_FILES
)
