set(SRC_FILES
    App.cpp
    Level.cpp
    LevelData.cpp
    PassCondition.cpp
    Screen/LobbyScreen.cpp
    Screen/SettingsScreen.cpp
    Screen/MenuScreen.cpp
    Screen/GameScreen.cpp
    Physics/PhysicsWorld.cpp
    Physics/PhysicalObject.cpp
    Physics/CompoundPhysicalObject.cpp
)

set(INCLUDE_FILES
    App.hpp
    Level.hpp
    LevelData.hpp
    PassCondition.hpp
    Screen/SettingsScreen.hpp
    Screen/LobbyScreen.hpp
    Screen/MenuScreen.hpp
    Screen/GameScreen.hpp
    Screen/UIScreen.hpp
    Physics/PhysicsWorld.hpp
    Physics/PhysicalObject.hpp
    Physics/CompoundPhysicalObject.hpp
)

set(TEST_FILES
)
